# Site settings
title: jojolin的博客
motto: 一个时代有一个时代的机会
email: ljzjojop@126.com
description: > # this means to ignore newlines until "baseurl:"
  分享快乐学习的知识和经验！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jzlin.com" # the base hostname & protocol for your site
github_username:  jojolin

# Build settings
markdown: kramdown
